language: android
android:
  components:
    - build-tools-26.0.2
    - android-27
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-21

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2


before_install:
  - yes | sdkmanager "platforms;android-27"
  MOBILSZOFTVER LABOR – TRAVIS CI 4 / 6
  Copyright © 2018. Ekler Péter, Forstner Bertalan, Balogh Tamás, Automatizálási és Alkalmazott Informatikai Tanszék


deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - heshenghai94@gmail.com
    on_success: always
    on_failure: always

